micronaut:
  application:
    name: micronautMercadoLivre
  security:
    enabled: true
    reject-not-found: false
    authentication: bearer
    token:
      jwt:
        generator:
          secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
          access-token:
            expiration: 1800

datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

#jpa.default.properties.hibernate.hbm2ddl.auto: update

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    entity-scan:
      packages: 'br.com.zup.academy.domain.model'